name: Demo Aidlink CI/CD
on:
  push:
    branches:
      - 'aidlink-demo'
  pull_request:
    branches:
      - 'aidlink-demo'
  workflow_dispatch:

env:
  CI: false

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'action') || contains(github.event.pull_request.title, 'action') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - name: Get short SHA and short Run ID
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "run_id_short=${GITHUB_RUN_ID:0:3}" >> $GITHUB_OUTPUT

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            github/data/general/docker/esatya username | DOCKERHUB_USERNAME ;
            github/data/general/docker/esatya password | DOCKERHUB_TOKEN ;

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm@8.14.1
          pnpm install
          npx nx reset
          pnpm prisma:generate
          pnpm build:all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Beneficiary Image
      - name: build && push beneficiary
        id: build-push-beneficiary
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.beneficiary
          # push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            esatya/rahat-platform-beneficiary:demo-aidlink
            esatya/rahat-platform-beneficiary:demo-aidlink-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.run_id_short }}

      # Rahat Image
      - name: build && push rahat
        id: build-push-rahat
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.rahat
          # push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: |
            esatya/rahat-platform-rahat:demo-aidlink
            esatya/rahat-platform-rahat:demo-aidlink-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.run_id_short }}
