name: Dev Rahat CI/CD
on:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - 'apps/beneficiary'
      - 'apps/beneficiary-e2e'

  pull_request:
    branches:
      - 'dev'
    paths-ignore:
      - 'apps/beneficiary'
      - 'apps/beneficiary-e2e'

env:
  CI: false
  env_npmrc: ${{ secrets.ENV_NPMRC }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: import env file
        run: |
          touch ./.npmrc && echo "$env_npmrc" >> ./.env

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm
          pnpm install
          prisma:generate
          pnpm build:rahat

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Rahat Image
      - name: build && push rahat
        id: build-push-rahat
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.rahat
          push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          tags: esatya/rahat-platform-rahat:dev
