name: Stage Root CI/CD
on:
  push:
    branches:
      - 'stage-aa'
  pull_request:
    branches:
      - 'stage-aa'
  workflow_dispatch:

env:
  CI: false
  env_npmrc: ${{ secrets.ENV_NPMRC }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'action') || contains(github.event.pull_request.title, 'action') || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - name: import env file
        run: |
          touch ./.npmrc && echo "$env_npmrc" >> ./.npmrc

      - uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: install dependencies and build apps
        run: |
          npm install -g pnpm@8.14.1
          pnpm install
          npx nx reset
          pnpm prisma:generate
          pnpm build:all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Beneficiary Image
      - name: build && push beneficiary
        id: build-push-beneficiary
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.beneficiary
          # push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: esatya/rahat-platform-beneficiary:stage-aa

      # Rahat Image
      - name: build && push rahat
        id: build-push-rahat
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.rahat
          # push: ${{ github.event_name == 'push' && 'true' || 'false' }}
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: esatya/rahat-platform-rahat:stage-aa
