name: Stage CI/CD
on:
  push:
    branches:
      - "stage"

  pull_request:
    branches:
      - "stage"

env:
  CI: false
  env_stage: ${{ secrets.ENV_STAGE }}

jobs:
  deploy:
    name: build docker image and push to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stage

      - name: create environment file
        run: |
          touch ./.env && echo "$env_stage" >> ./.env

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push web
        id: build-push-web
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: esatya/rahat-api:stage

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t myimage:${{ github.sha }} .