name: AA Test Load

on:
  workflow_dispatch:

jobs:
  call-core:
    uses: rahataid/rahat-platform/.github/workflows/AA-Core-CICD.yaml@test-load
    with:
      apps_to_build: beneficiary,rahat
      tag_suffix: test-load
      env_secret_name: ENV_AA_TEST_LOAD
    secrets: inherit
